### ISSUE TITLE
make all Error

### ISSUE THREAD

**Issue by todest** [adepierre/Botcraft#17]
I ran into an error while following the build instructions, any help would be appreciated. :)

gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

Error occured while running make all:
https://pastebin.com/EmRTBngL

**Comment by adepierre** [comment]
It seems to be very similar to #5 but with a link error from openSSL instead of protocolcraft.

From what I see, you don't seem to have openSSL on your computer, so botcraft is using the included one, but can't link to it afterward. I'll try to see what I can do.

In the meantime, you can try either try to:

- install openssl directly on your system or
- manually add the magical line ``set_property(TARGET ssl // crypto PROPERTY POSITION_INDEPENDENT_CODE ON)`` after the ``add_library`` in both ``3rparty/openssl/ssl`` and ``3rdparty/openssl/crypto``

**Comment by todest** [comment]
I sawed OpenSSL has been installed in my system, and I reinstalled it, but it didn't work. So i used the second solution, it succeed, Cheers.

**Comment by adepierre** [comment]
Yes botcraft installs openSSL if it does not find it. But only locally, not on your system. And this local installation is apparently not working because of the PIC thing

Glad it solves the problem for you, will try to fix it.

**Comment by maxsupermanhd** [comment]
Same but with `glad`, can not find a setting for one...

**Comment by adepierre** [comment]
@maxsupermanhd could you elaborate on your error? Is the glad library found on your system or is it the one included in this repo that is built?

If it's not on your system, you should have a message ``Can't find glad, building it from sources`` the first time you call cmake.

**Comment by maxsupermanhd** [comment]
For some reason it decided to build it's own version even if I have one installed, here is full log:
```
make -j4
[ 33%] Built target protocolCraft
[ 35%] Linking CXX shared library ../../bin/libbotcraft.so
/usr/bin/ld: ../3rdparty/glad/install/lib/libglad.a(glad.c.o): relocation R_X86_64_PC32 against symbol `glad_glGetString' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [botcraft/CMakeFiles/botcraft.dir/build.make:526: ../bin/libbotcraft.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:244: botcraft/CMakeFiles/botcraft.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by adepierre** [comment]
Ok thanks for the details. I'm currently working on a fix that should work for both openssl and glad.

Where did you add ``-DCMAKE_CXX_FLAGS=-fPIC``? Because dependencies are built in a separate cmake process (for example [here](https://github.com/adepierre/Botcraft/blob/bbbb1b22e349c3b4da064e4e1e5bdac139e73103/cmake/glad.cmake#L16) for glad). If you added it in the botcraft cmake call, it would just tell cmake to add -fPIC to protocolCraft and botcraft, which already have it. And btw, I think that a more "cmakeish" way of doing it would be ``-DCMAKE_POSITION_INDEPENDENT_CODE=ON``.

**Comment by adepierre** [comment]
I've added the cmake line to make both openssl and glad compiled with -fPIC, so it should solve both issues.

I've also added it to zlib as I assume the problem would have been the same. Please let me know if this works for you in a fresh build!

**Comment by maxsupermanhd** [comment]
Yep, with latest fixes everything seems to be building fine, thanks!

**Comment by maxsupermanhd** [comment]
... Aaand I was wrong, ImGui has same problem...

**Comment by adepierre** [comment]
Obviously I though about zlib but not imgui 😑

Wait for it
