### ISSUE TITLE
Binaries should not be tied down to location of repository

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#52]
Cmake build system made possible to build projects from outside of root directory in order to have several builds saved, technique with all binaries in project root under ./bin/ is horrible and should be reconsidered.

**Comment by adepierre** [comment]
Yeah I agree it's not ideal. The main problem here is that the exe expects the assets to be located at ``../Assets/<version>`` so if the output is moved, nothing would work.

I might eventually rework this system one day, perhaps by copying all the required assets at the right location, but this is clearly not a priority.

**Comment by maxsupermanhd** [comment]
Why not move assets with binary? Or store them in user-based storage like in ~/.local/share

Not that this is very bad but it is super annoying to deal with. You also can bake assets right into binary, not only it can speed stuff up but will provide self-contained binary that relies on no environment

**Comment by adepierre** [comment]
Yes moving the assets with binary is what I meant when I said "copying the required assets". I think this is the best approach.

I'm not a fan of user based storage because of two reasons:

1. you need to write OS-specific code to deal with it
2. removing botcraft from a computer is generally done by simply deleting a folder, and I'd like to keep it this way so there are no lost files lying you don't know where

**Comment by adepierre** [comment]
Fix with latest version. You can use ``BOTCRAFT_OUTPUT_DIR`` in cmake to specify a custom output folder.
