### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#54]
If I want to use my own logging I can not do it properly because library contains a lot of raw prints.

I want to make a terminal control with my libraries (https://github.com/maxsupermanhd/liveterm or https://github.com/maxsupermanhd/cterminal) but how can I overload printf or huh?

**Comment by maxsupermanhd** [comment]
How about move all logging to P7 logging library, it will open a lot of new possibilities. As I've seen now there is just occasional std::cout and std::cerr piping but not much structure. What are you thinking about it?

**Comment by adepierre** [comment]
To be honest, I didn't have any time to think about that.

Right now I'm still refactoring all the AI/task system. There is also all the stuff with the Entities that I need to develop. And in addition there is an issue (#49 ) that needs to be fixed, and the location of the output you mentioned in another issue that I'd like to fix because I agree that's not ideal. This improvement is thus behind a lot of things in my todo list.

Besides that, the whole point of this library for me is doing things to learn. That's why I'm trying to keep the number of external dependencies as low as possible. So it's unlikely that I'll add one like P7 just for logging stuff, and rather develop something custom. Will it be as efficient and powerful as a specialised third party? No way. Will it be more interesting for me? Yes.

**Comment by adepierre** [comment]
I'm not sure this is the right time to do this as things will be changed with the new behaviour system, I think it would be wiser to wait for that before trying this kind of things impacting many files.

**Comment by maxsupermanhd** [comment]
Ok, waiting for a bunch of new prints to logs to sort out. Longer logging is delayed - harder it is to rake.

**Comment by adepierre** [comment]
Well in my point of view it's not even in the scope of this library so it's not really an issue to delay that.

From what I've read from all the issues you've opened, I think you should consider creating your own fork of Botcraft and do whatever you want to with it without bothering with my slowness.

**Comment by maxsupermanhd** [comment]
No, if you want to call Botcraft a library it must have primitive capabilities of integration. Dropping random junk to stdout (sometimes even without \n on the end) is not acceptable.

**Comment by adepierre** [comment]
Ok so don't call it a library, fine. No problem.

I just code it for fun and because that interests me. I don't have the ambition to make it perfect or even usable for anyone other than me. I made the code open source because I thought it could interest other people and be useful for them.

Now if it's not for you, then just use another library that meets your criteria or build your own.
