### ISSUE TITLE
Rate limiting because of re-requesting of Minecraft token

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#58]
There is no cache for mc token so it is requested every time. It makes xbl, xsts and mc services rate limit requests if intense testing is performed.

**Comment by adepierre** [comment]
This should be fixed with the latest push. I completed your PR with a more generic system to handle both Mojang and Microsoft accounts.

I also took the opportunity to add an optional ``force_microsoft_account`` boolean to the ``Connect`` method allowing you to use the ``login`` field to distinguish one account from the other, solving #59 without having to rename the cache file.

Once again, I don't own a Microsoft account, and even less multiple ones so I didn't test it, but as I used your PR I guess it should be good. Feel free to reopen if it's not.
