### ISSUE TITLE
Error: "Protocol version not implemented"

### ISSUE THREAD

**Issue by Camezza** [adepierre/Botcraft#6]
Hi, I received an error while compiling the following code in main.cpp:
https://hastebin.com/rujakufawo.cpp

Error:
https://hastebin.com/tuqizudode.sql

OS: Ubuntu 20.04.1 LTS 64 bit

Any help would be much appreciated!

**Comment by adepierre** [comment]
This means that the PROTOCOL_VERSION variable is either not defined or defined with an unknown value when you compile your code.

**Comment by Camezza** [comment]
Where and how do I define it?

**Comment by adepierre** [comment]
It's done by cmake when you link your executable to botcraft. Check the examples.

**Comment by Camezza** [comment]
I still get the same error compiling the examples.

**Comment by adepierre** [comment]
Are you using the given building procedure as written in the readme? And you're getting this error?

```
git clone https://github.com/adepierre/Botcraft.git
cd Botcraft
mkdir build
cd build
cmake -DGAME_VERSION=1.16.3 -DBOTCRAFT_BUILD_EXAMPLES=ON -DBOTCRAFT_COMPRESSION=ON -DBOTCRAFT_ENCRYPTION=ON -DBOTCRAFT_USE_OPENGL_GUI=OFF ..
make all
```

**Comment by Camezza** [comment]
Yep, followed it again and still same error

**Comment by adepierre** [comment]
That's weird I can't reproduce it, everything is fine on my side. Which version of cmake do you have?

**Comment by Camezza** [comment]
cmake version 3.17.3, compiled using CLion. I'll make another fresh build and see if I get anywhere

**Comment by adepierre** [comment]
This [stackoverflow issue](https://stackoverflow.com/questions/58059531/clion-does-not-pick-up-complex-pre-processor-definitions) looks like your problem a lot. So I guess it's more a CLion limitation/error than a botcraft one.

As a workaround you could set up your own preprocessor variable ``PROTOCOL_VERSION`` to the correct protocol number (753 for 1.16.3 for example). But you would have to change it everytime you would like to change the version instead of cmake doing it for you. And you might also have some troubles with compression, encryption and GUI variable as well.

**Comment by Camezza** [comment]
I see, well that's a shame... I'll use a different IDE as a workaround for now, thanks for your help. :)

**Comment by Camezza** [comment]
I still get the same errors using QT Creator IDE, too
