### ISSUE TITLE
wrong position used in map, dirty-fixes

### ISSUE THREAD

**Issue by JackOBIsReal** [adepierre/Botcraft#63]
It looks like the `Chunk::block_entities_data` map has the _world_ position as a key (example, I have a world where at position 9, 68, -11 there is a sign), but when I step through the function calls the `Chunk::GetBlockEntityData` gets the position _within the chunk_ (9, 68, 5), and therefore it doesn't find the sign in the entities data map. I have dirty-fixed it by changing lines 591 and 603 in Botcraft\botcraft\src\Game\World\World.cpp to not use your `pos.x % chunk_width... snake` but instead just handing down the original positions. I am a bit afraid of adding a pull request because I wasn't able to find the code filling up that map in the first place so I have no idea if my "fixes" break anything, can you tell me where that code is? I have also changed another thing in the InventoryManager that fixed the actual issue I had without being able to verify that I haven't accidentally broke something, do you have any tests or something like that I could use?

**Comment by adepierre** [comment]
You're totally right about the first bug, I saw it quite some time ago now. I thought it was already fixed, but it seems that it never made it to master. The underlying issue is that the server sends the block entity data per chunk, but indexed with _world_ coordinates, not chunk ones. I think the proper way to fix that would be to directly convert the world coords into chunk ones when they are loaded from the packet. The function is [here](https://github.com/adepierre/Botcraft/blob/4a0b1c30bc0b226cc5a21472362def83453a4894/botcraft/src/Game/World/Chunk.cpp#L301), and is called from the packet Handle [here](https://github.com/adepierre/Botcraft/blob/4a0b1c30bc0b226cc5a21472362def83453a4894/botcraft/src/Game/World/World.cpp#L882). Don't worry for the PR just for that, I'll try to make the modification and push it tomorrow. I also wanted to make more tests anyway to check if it's always in world coords for all supported versions of the game because I find it a bit odd.

Considering the InventoryManager, could you detail what the issue was, and how did you solve it? You can do it in a PR it might be easier to exchange directly from your code.

And unfortunately no, there is no automated tests for botcraft unfortunately as it requires a server. I have a test server that I usually load just to play around and see if things still work. But nothing fancy.

**Comment by adepierre** [comment]
The world/chunk coords issue should be fixed with latest commits, if you can confirm it's ok for you too so this issue can be closed, thanks.

**Comment by adepierre** [comment]
I guess no response means it doesn't explode anymore. Feel free to reopen if the bug is still present.
