### ISSUE TITLE
Unable to compile - Zlib

### ISSUE THREAD

**Issue by SaubereSache** [adepierre/Botcraft#65]
Hello,

I'm unable to compile your project (tried Windows and WSL).
It seems like ZLIB is missing / improperly configured in the CMake file.

![image](https://user-images.githubusercontent.com/53787471/145436821-6a659a29-c013-4752-94d2-137240d9bc88.png)

Many thanks for your assistance!

**Comment by adepierre** [comment]
I've no problem with Windows. Could you check the value of the ``ZLIB_INCLUDE_DIR`` variable in cmake?

**Comment by SaubereSache** [comment]
The variable ZLIB_INCLUDE_DIR (found in `build/CMakeCache.txt`) has the value `C:/Users/Constantin Schreiber/CLionProjects/Botcraft/build/3rdparty/zlib/install/include`, which seems to be populated.

**Comment by adepierre** [comment]
Ok so that means that you don't have Zlib installed on your computer, and cmake did the checkout and local installation during configuration. The weird thing is that it's exactly the same thing that the Windows action on github does, and it works 🤔

Could you detail your build setup? (OS, compiler, cmake, versions etc...)

I'll try to see if I can reproduce the error to see where it comes from.

**Comment by SaubereSache** [comment]
I think I found the issue, seems like you aren't quoting paths in your CMake files properly (e. g. `${BOTCRAFT_OUTPUT_DIR}/bin/Assets/${GAME_VERSION}/custom/`), which breaks things due to my Windows-Username containing a space.
I'll try changing the CMake Files and will submit a PR if it works ^^
