### ISSUE TITLE
Can't build on linux: undefined reference to `dlclose'

### ISSUE THREAD

**Issue by cnharrison** [adepierre/Botcraft#69]
Heya! Having these problems building on Linux: 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/4341988/151179038-3564608b-d0fb-46c6-a501-9944ce46e6e3.png">

I'm on WSL at the moment but also tried on non-WSL Ubuntu VM and got the same issue. Am I doing something wrong?

**Comment by adepierre** [comment]
That's weird it doesn't occur in the github action build for linux 🤔

It seems that the library is successfully built, it's just the examples that can't link to it.

I'll try to DL a VM tonight to see if I can reproduce the error to find the root cause. In the meantime, could you try to add:

``Examples/0_HelloWorld/CMakeLists.txt:l11``
```
target_link_libraries(0_HelloWorld ${CMAKE_DL_LIBS})
```

I guess it should fix your build issue. You might have to add the same line for the other examples too.
